version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: "rails"
    commit-message:
      prefix: Dependencies
